# R script for Tutorial 2, week 6, Biodiversity Under Pressure course
# written by: Helen Alexander, Oct. 2023

# This script implements a stochastic model of a spillover event and subsequent
# outbreak in a focal host population.
# 1. random waiting time for a single spillover event (pathogen introduction) 
# from a reservoir host population into a focal host population, assuming a
# constant rate of introductions
# 2. random number of secondary infections generated by the first infected host,
# using the model of host heterogeneity from Lloyd-Smith et al. 2005
# 3. random number of infected hosts in the subsequent transmission chain,
# according to the infection model from part 2 above, tracked in discrete time 
# ('infection generations')


###### EXERCISE 1 ######
# waiting time for spillover

# input parameters
spill.rate <- 5  # average number of spillovers per unit time (e.g. year)
num.draws <- 100   # number of trials (random draws)

# randomly draw the waiting time for a spillover
wait.time <- rexp(n=num.draws,rate=spill.rate)

# print/plot the results
if(num.draws <= 10){ # one or few draws: print all wait times individually
  print(paste("waiting time(s): ",round(wait.time,digits=3),sep=""))
}
if(num.draws >1) {   # multiple draws: print mean and plot histogram
  print(paste("mean waiting time = ",round(mean(wait.time),digits=3),sep = ""))
  hist(wait.time)
}


###### EXERCISE 2 ######
# secondary infections per host

# input parameters
R0 <- 1.5   # mean number of secondary infections per host
var.par <- 100   # parameter controlling variation amongst hosts
num.draws <- 100000  # number of draws/hosts to draw their number of secondary infections

# randomly draw the number of secondary infections per host
infections <- rnbinom(n=num.draws,size=1/var.par,mu=R0)


# print the result if only one draw
if(num.draws==1){ print(infections) }

# if multiple draws, output some summary stats and plot the distribution
if(num.draws > 1){
  print(paste("min =",min(infections), sep=" ")); print(paste("max =",max(infections), sep=" ")); print(paste("mean =",mean(infections), sep=" "))
  hist(infections,breaks=seq(from=-0.5,to=max(infections)+0.5,by=1),probability=T,xlab="number of secondary infections",ylab="proportion of cases")
}


###### EXERCISE 3 ######
# outbreak size

### (a) Simulate and plot one transmission chain

# Main input parameters - distribution of secondary infections
R0 <- 1.5   # mean number of secondary infections per host
var.par <- 1   # parameter controlling variation amongst hosts

# Additional input parameters - simulation settings
max.gens <- 20  # maximum number of infection generations to simulate
max.N <- 1000   # max number of infected hosts (in one generation) to simulate

# create vectors to store number of infected hosts
num.inf <- numeric(length=max.gens+1)    # number currently infected in each generation
cumul.inf <- numeric(length=max.gens+1)  # cumulative number infected
# start both of these at 1
num.inf[1] <- 1
cumul.inf[1] <- 1

# simulate
for(gen in 1:max.gens){  # loop over infection generations
  
  # draw random number of secondary infections generated by each host in previous generation
  new.inf.list <- rnbinom(n=num.inf[gen],size=1/var.par,mu=R0)
  
  # add up the total number of new infections in the new generation and store this in num.inf
  new.inf.tot <- sum(new.inf.list)
  num.inf[gen+1] <- new.inf.tot
  cumul.inf[gen+1] <- cumul.inf[gen] + new.inf.tot
  #num.inf <- c(num.inf,new.inf.tot)
  #cumul.inf <- c(cumul.inf,cumul.inf[gen]+new.inf.tot)
  
  if(new.inf.tot==0){  # if there are no new infections in this generation, the outbreak has died out and we can stop simulating
    cumul.inf[(gen+2):(max.gens+1)] <- cumul.inf[gen+1]
    break
  }
  
  if(new.inf.tot > max.N){  # if we have reached the max number
    num.inf <- num.inf[1:(gen+1)]  # truncate num.inf at the last simulated generation
    cumul.inf <- cumul.inf[1:(gen+1)]
    break  # stop simulating
  }
  
}

# check final generation in simulation (useful for plotting)
end.gen <- length(num.inf)-1

# PLOT: current and cumulative number of infected hosts over time (infection generations)
# Note that there are multiple plotting options here. Run one option at a time to get the plot you want.

# current number infected hosts - linear scale
plot(0:max.gens,0:max.gens,type="n",ylim=c(0,max(num.inf)+1),xlab="infection generation",ylab="number of infected hosts")
lines(0:end.gen,num.inf,type="s",lwd=4,col='red')
# - log scale
plot(0:max.gens,0.01+0:max.gens,log="y",type="n",ylim=c(0.9,max(num.inf)+1),xlab="infection generation",ylab="number of infected hosts")
lines(0:end.gen,num.inf+0.01,type="s",lwd=4,col='red')

# cumulative number of infected hosts - linear scale
plot(0:max.gens,0:max.gens,type="n",ylim=c(0,max(cumul.inf)+1),xlab="infection generation",ylab="cumulative number of infected hosts")
lines(0:end.gen,cumul.inf,type="s",lwd=4,col='red')
# - log scale
plot(0:max.gens,0.01+0:max.gens,log="y",type="n",ylim=c(0.9,max(cumul.inf)+1),xlab="infection generation",ylab="cumulative number of infected hosts")
lines(0:end.gen,cumul.inf+0.01,type="s",lwd=4,col='red')


### (b) Simulate a set of simulations at fixed R0 and var.par and calculate summary statistics

# Main input parameters - distribution of secondary infections
R0 <- 1.5   # mean number of secondary infections per host
var.par <- 1   # parameter controlling variation amongst hosts

# Additional input parameters - simulation settings
max.gens <- 20   # maximum number of infection generations to simulate
max.N <- 1000    # max number of infected hosts (in one generation) to simulate
num.sims <- 100  # number of simulations to run at a given parameter set

# define variables to store outputs of interest from each simulation
end.gen <- numeric(length=num.sims)       # final simulated generation
num.inf.peak <- numeric(length=num.sims)  # maximum number of infected hosts in any single generation
num.inf.end <- numeric(length=num.sims)   # number of infected hosts in the final simulated generation
outbreak.size <- numeric(length=num.sims) # cumulative number of infected hosts by the end of the simulation

# simulate
for(sim in 1:num.sims){  # loop over simulation runs
  
  # Create vectors to store number of infected hosts. Note: these will get over-written by each simulation loop.
  num.inf <- numeric(length=max.gens+1)    # number currently infected in each generation
  cumul.inf <- numeric(length=max.gens+1)  # cumulative number infected
  # start both of these at 1
  num.inf[1] <- 1
  cumul.inf[1] <- 1
  
  for(gen in 1:max.gens){  # loop over infection generations
   
    # draw random number of secondary infections generated by each host in previous generation
    new.inf.list <- rnbinom(n=num.inf[gen],size=1/var.par,mu=R0)
    
    # add up the total number of new infections in the new generation and store this in num.inf
    new.inf.tot <- sum(new.inf.list)
    num.inf[gen+1] <- new.inf.tot
    cumul.inf[gen+1] <- cumul.inf[gen] + new.inf.tot
    
    if(new.inf.tot==0){  # if there are no new infections in this generation, the outbreak has died out and we can stop simulating
      cumul.inf[(gen+2):(max.gens+1)] <- cumul.inf[gen+1]
      break
    }
    
    if(new.inf.tot > max.N){  # if we have reached the max number
      num.inf <- num.inf[1:(gen+1)]     # truncate num.inf at the last simulated generation
      cumul.inf <- cumul.inf[1:(gen+1)] # truncate cumul.inf
      break  # stop simulating
    }
     
  }  # end loop over gen for current simulation
  
  # store summary statistics about this simulation
  end.gen[sim] <- gen
  num.inf.peak[sim] <- max(num.inf)
  num.inf.end[sim] <- rev(num.inf)[1]
  outbreak.size[sim] <- rev(cumul.inf)[1]
  
}  # end loop over simulations

# identify which simulations went extinct and which did not (lists of sim numbers) 
#- this will be used repeatedly below
sims.extinct <- which(num.inf.end==0)
sims.active <- which(num.inf.end > 0)

# Analyse the output stats

# What fraction of simulated outbreaks went extinct?
frac.extinct <- sum(num.inf.end==0)/num.sims
print(paste("fraction extinct: ",frac.extinct,sep=""))

# Amongst outbreaks that went extinct, in which generation did this occur?
gen.extinct <- end.gen[sims.extinct]
hist(gen.extinct,breaks=seq(from=0.5,to=max(gen.extinct)+0.5,by=1),probability=T)
# summary stats:
print(paste("median extinction time: ",median(gen.extinct),"; maximum extinction time: ",max(gen.extinct),sep=""))

# What was the peak number of infected individuals in any generation?
# look at all simulations together:
hist(num.inf.peak)
# look only at outbreaks that went extinct:
peak.extinct <- num.inf.peak[sims.extinct]
hist(peak.extinct,breaks=seq(from=0.5,to=max(peak.extinct)+0.5,by=1))
print(paste("peak number infected if outbreak went extinct: median = ",median(peak.extinct),sep=""))
# look only at outbreaks that remained active (not extinct) by the end of the simulation:
peak.active <- num.inf.peak[sims.active]
hist(peak.active)
print(paste("peak number infected if outbreak still active: median = ",median(peak.active),sep=""))

# What was the total outbreak size, i.e. cumulative number of infected hosts, by the end of the simulation?
# look at all simulations together:
hist(outbreak.size)
# look only at outbreaks that went extinct:
outbreak.size.extinct <- outbreak.size[sims.extinct]
hist(outbreak.size.extinct,breaks=seq(from=0.5,to=max(outbreak.size.extinct)+0.5,by=1))
print(paste("Outbreak sizes for extinct outbreaks: median = ",median(outbreak.size.extinct),
            "; min = ",min(outbreak.size.extinct), "; max = ",max(outbreak.size.extinct),sep=""))
# look only at outbreaks that remained active (not extinct) by the end of the simulation:
outbreak.size.active <- outbreak.size[sims.active]
hist(outbreak.size.active)
print(paste("Outbreak sizes for active outbreaks: median = ",median(outbreak.size.active),
            "; min = ",min(outbreak.size.active), "; max = ",max(outbreak.size.active),sep=""))

